# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

check: format-check lint typecheck

fix: format lint-fix

# ---
# Setup

setup: setup-uv

setup-uv:
    uv sync --locked --all-extras --dev

# ---
# Build

build: build-python

build-python:
    uv build

# ---
# Format

format: format-python format-markdown

format-python:
    uv run ruff format

format-markdown:
    uv run rumdl fmt

format-check: format-check-python format-check-markdown

format-check-python:
    uv run ruff format --check

format-check-markdown:
    uv run rumdl fmt --check

# ---
# Lint

lint: lint-python lint-markdown

lint-python: 
    uv run ruff check

lint-markdown:
    uv run rumdl check

lint-fix: lint-fix-python lint-fix-markdown

lint-fix-python: 
    uv run ruff check --fix

lint-fix-markdown: 
    uv run rumdl check --fix


# ---
# Typecheck

typecheck: typecheck-python

typecheck-python:
    uv run ty check

# ---
# Test

test: test-python

test-python:
    uv run pytest