#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Converters Hex CI

on:
  push:
    branches: ["main"]
    paths:
      - "converters/hex/**"
      - "python/**"
      - ".github/**"
  pull_request:
    branches: ["main"]
    paths:
      - "converters/hex/**"
      - "python/**"
      - ".github/**"

env:
  UV_VERSION: "0.12.5"
  PYTHON_VERSION: "3.14"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: converters/hex
    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv and python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          working-directory: converters/hex
      - name: Install project
        run: uv sync --locked --all-extras --dev
      - name: Run checks
        run: uv run poe check

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: converters/hex
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv and python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          working-directory: converters/hex
      - name: Install project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run poe test

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: converters/hex
    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv and python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          working-directory: converters/hex
      - name: Build distribution
        run: uv build
